# Generated by Django 4.1.2 on 2022-10-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innerinsta', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instadata',
            new_name='data',
        ),
    ]
