# Generated by Django 4.1.2 on 2022-10-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innerinsta', '0002_rename_instadata_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
